clone_depth: 1

install:
    - cd c:\

    # # Install Boost libraries
    # - appveyor-retry nuget install boost_atomic-vc120 -Version 1.61.0
    # - appveyor-retry nuget install boost_system-vc120 -Version 1.61.0
    # - appveyor-retry nuget install boost_filesystem-vc120 -Version 1.61.0
    # - appveyor-retry nuget install boost_chrono-vc120 -Version 1.61.0
    # - appveyor-retry nuget install boost_date_time-vc120 -Version 1.61.0
    # - appveyor-retry nuget install boost_thread-vc120 -Version 1.61.0
    # - appveyor-retry nuget install Doxygen -Version 1.8.14

build_script:
    - dir
    - cd c:\projects\gnuradio-windows-build-scripts
    # - set PATH=%PATH%;C:\Doxygen
    # - ps: Set-ExecutionPolicy Unrestricted
    - ps: .\RUNME_AUTO.ps1
    # Push it!
    - cd c:\grb
    - ps: cp C:\grb\src-stage4-installer\dist\Release\*.msi gnuradio_3_7_11_iiosupport.msi
    - appveyor PushArtifact c:\grb\gnuradio_3_7_11_iiosupport.msi
